# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pedido.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 592)
        Form.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.tb_peidos = QtWidgets.QTableWidget(Form)
        self.tb_peidos.setGeometry(QtCore.QRect(0, 10, 421, 401))
        self.tb_peidos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tb_peidos.setObjectName("tb_peidos")
        self.tb_peidos.setColumnCount(4)
        self.tb_peidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_peidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_peidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_peidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_peidos.setHorizontalHeaderItem(3, item)
        self.bt_pedido = QtWidgets.QPushButton(Form)
        self.bt_pedido.setGeometry(QtCore.QRect(550, 570, 75, 23))
        self.bt_pedido.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.bt_pedido.setObjectName("bt_pedido")
        self.bt_mudar = QtWidgets.QPushButton(Form)
        self.bt_mudar.setGeometry(QtCore.QRect(0, 570, 75, 23))
        self.bt_mudar.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.bt_mudar.setObjectName("bt_mudar")
        self.bt_consulta = QtWidgets.QPushButton(Form)
        self.bt_consulta.setGeometry(QtCore.QRect(240, 570, 141, 23))
        self.bt_consulta.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.bt_consulta.setObjectName("bt_consulta")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tb_peidos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "pedido"))
        item = self.tb_peidos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "valor"))
        item = self.tb_peidos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "metodo de pagamento"))
        item = self.tb_peidos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "tipo de retirada"))
        self.bt_pedido.setText(_translate("Form", "novo pedido"))
        self.bt_mudar.setText(_translate("Form", "mudar pedido"))
        self.bt_consulta.setText(_translate("Form", "consulta de clientes"))
