# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pedidoI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pedidoI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 592)
        Form.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.tb_pedido = QtWidgets.QTableWidget(Form)
        self.tb_pedido.setGeometry(QtCore.QRect(0, 0, 621, 401))
        self.tb_pedido.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tb_pedido.setObjectName("tb_pedido")
        self.tb_pedido.setColumnCount(4)
        self.tb_pedido.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_pedido.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_pedido.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_pedido.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_pedido.setHorizontalHeaderItem(3, item)
        self.bt_novo = QtWidgets.QPushButton(Form)
        self.bt_novo.setGeometry(QtCore.QRect(550, 570, 75, 23))
        self.bt_novo.setStyleSheet("background-color: rgb(116, 116, 116);")
        self.bt_novo.setObjectName("bt_novo")
        self.bt_mudar = QtWidgets.QPushButton(Form)
        self.bt_mudar.setGeometry(QtCore.QRect(0, 570, 75, 23))
        self.bt_mudar.setStyleSheet("background-color: rgb(116, 116, 116);")
        self.bt_mudar.setObjectName("bt_mudar")
        self.bt_consulta = QtWidgets.QPushButton(Form)
        self.bt_consulta.setGeometry(QtCore.QRect(240, 570, 141, 23))
        self.bt_consulta.setStyleSheet("background-color: rgb(116, 116, 116);")
        self.bt_consulta.setObjectName("bt_consulta")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tb_pedido.horizontalHeaderItem(0)
        item.setText(_translate("Form", "pedido"))
        item = self.tb_pedido.horizontalHeaderItem(1)
        item.setText(_translate("Form", "valor"))
        item = self.tb_pedido.horizontalHeaderItem(2)
        item.setText(_translate("Form", "pagamento"))
        item = self.tb_pedido.horizontalHeaderItem(3)
        item.setText(_translate("Form", "tipo de retirada"))
        self.bt_novo.setText(_translate("Form", "novo pedido"))
        self.bt_mudar.setText(_translate("Form", "mudar pedido"))
        self.bt_consulta.setText(_translate("Form", "consulta de clientes"))
