# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(209, 205)
        Form.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.select = QtWidgets.QLabel(Form)
        self.select.setGeometry(QtCore.QRect(9, 9, 110, 16))
        self.select.setObjectName("select")
        self.bt_fechar = QtWidgets.QPushButton(Form)
        self.bt_fechar.setGeometry(QtCore.QRect(120, 180, 75, 23))
        self.bt_fechar.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.bt_fechar.setObjectName("bt_fechar")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 30, 81, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_admin = QtWidgets.QPushButton(self.widget)
        self.bt_admin.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.bt_admin.setObjectName("bt_admin")
        self.verticalLayout.addWidget(self.bt_admin)
        self.bt_pedidos = QtWidgets.QPushButton(self.widget)
        self.bt_pedidos.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.bt_pedidos.setObjectName("bt_pedidos")
        self.verticalLayout.addWidget(self.bt_pedidos)
        self.bt_balcao = QtWidgets.QPushButton(self.widget)
        self.bt_balcao.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.bt_balcao.setObjectName("bt_balcao")
        self.verticalLayout.addWidget(self.bt_balcao)
        self.bt_caixa = QtWidgets.QPushButton(self.widget)
        self.bt_caixa.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.bt_caixa.setObjectName("bt_caixa")
        self.verticalLayout.addWidget(self.bt_caixa)
        self.bt_desen = QtWidgets.QPushButton(self.widget)
        self.bt_desen.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.bt_desen.setObjectName("bt_desen")
        self.verticalLayout.addWidget(self.bt_desen)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.select.setText(_translate("Form", "SELECIONE A FUNÇÃO"))
        self.bt_fechar.setText(_translate("Form", "fechar"))
        self.bt_admin.setText(_translate("Form", "administrador"))
        self.bt_pedidos.setText(_translate("Form", "pedidos"))
        self.bt_balcao.setText(_translate("Form", "balcão"))
        self.bt_caixa.setText(_translate("Form", "caixa"))
        self.bt_desen.setText(_translate("Form", "desenvolvedor"))
