# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transferencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transfer(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 400)
        Form.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 70, 265, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_atual = QtWidgets.QLineEdit(self.widget)
        self.lne_atual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_atual.setObjectName("lne_atual")
        self.horizontalLayout.addWidget(self.lne_atual)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(0, 110, 311, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_transfe = QtWidgets.QLineEdit(self.widget1)
        self.lne_transfe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_transfe.setObjectName("lne_transfe")
        self.horizontalLayout_2.addWidget(self.lne_transfe)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(400, 370, 158, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_cancela = QtWidgets.QPushButton(self.widget2)
        self.bt_cancela.setStyleSheet("background-color: rgb(139, 139, 139);")
        self.bt_cancela.setObjectName("bt_cancela")
        self.horizontalLayout_3.addWidget(self.bt_cancela)
        self.bt_transfer = QtWidgets.QPushButton(self.widget2)
        self.bt_transfer.setStyleSheet("background-color: rgb(139, 139, 139);")
        self.bt_transfer.setObjectName("bt_transfer")
        self.horizontalLayout_3.addWidget(self.bt_transfer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "número da comanda atual"))
        self.label_2.setText(_translate("Form", "número da comanda para transferir"))
        self.bt_cancela.setText(_translate("Form", "cancelar"))
        self.bt_transfer.setText(_translate("Form", "transferir"))
